version: "3.8"

services:
  hbbs:
    image: rustdesk/rustdesk-server:latest
    container_name: hbbs
    restart: unless-stopped
    environment:
      - RUST_LOG=info
      - HBBS_PORT=8190        # hbbs custom port
      - HBBR_PORT=8192        # tells hbbs where hbbr listens
    command: hbbs
    ports:
      - "8190:8190"           # TCP for hbbs
      - "8190:8190/udp"       # UDP for NAT traversal
      - "8192:8192"           # used by hbbr
    volumes:
      - ./data:/root/.config/rustdesk

  hbbr:
    image: rustdesk/rustdesk-server:latest
    container_name: hbbr
    restart: unless-stopped
    environment:
      - RUST_LOG=info
      - HBBR_PORT=8192        # hbbr custom port
    command: hbbr
    ports:
      - "8192:8192"           # TCP for hbbr relay
    volumes:
      - ./data:/root/.config/rustdesk
