services:
  hbbs:
    image: rustdesk/rustdesk-server:latest
    container_name: hbbs
    restart: unless-stopped
    environment:
      - RUST_LOG=info
      - HBBS_PORT=8190          # Custom ID/Signaling port
      - HBBR_PORT=8192          # Tells hbbs where hbbr listens
    command: hbbs -k _
    ports:
      # Custom ports - Essential for your setup
      - "8190:8190"             # TCP for hbbs ID/Signaling
      - "8190:8190/udp"         # UDP for NAT traversal
      # Default RustDesk ports - Included for convenience (optional)
      - "21115:21115"
      - "21116:21116"
      - "21117:21117/udp"
    volumes:
      - ./data:/root/.config/rustdesk

  hbbr:
    image: rustdesk/rustdesk-server:latest
    container_name: hbbr
    restart: unless-stopped
    environment:
      - RUST_LOG=info
      - HBBR_PORT=8192          # Custom Relay port
    command: hbbr -k _
    ports:
      # Custom ports - Essential for your setup
      - "8192:8192"             # TCP for hbbr relay
      - "8192:8192/udp"         # UDP for hbbr relay (REQUIRED)
      # Default RustDesk port - Included for convenience (optional)
      - "21117:21117"
    volumes:
      - ./data:/root/.config/rustdesk
