version: "3.8"

services:
  hbbs:
    image: rustdesk/rustdesk-server:latest
    container_name: hbbs
    restart: unless-stopped
    environment:
      - RUST_LOG=info
      - HBBS_PORT=8190        # custom port for hbbs
      - HBBR_PORT=8191        # hbbr relay port
    command: hbbs
    ports:
      - "8190:8190"           # TCP for hbbs
      - "8190:8190/udp"       # UDP for NAT traversal
      - "8191:8191"           # connection to hbbr relay
    volumes:
      - ./data:/root/.config/rustdesk

  hbbr:
    image: rustdesk/rustdesk-server:latest
    container_name: hbbr
    restart: unless-stopped
    environment:
      - RUST_LOG=info
      - HBBR_PORT=8191        # custom port for hbbr relay
    command: hbbr
    ports:
      - "8191:8191"           # TCP for hbbr relay
    volumes:
      - ./data:/root/.config/rustdesk
