# version: '3'

networks:
  rustdesk-net:
    external: false

services:
  hbbr:
    container_name: hbbr
    build: .
    # Use a local tag to ensure Compose uses the Dockerfile in this repo
    image: rustdesk/rustdesk-server:local
    command: hbbr
    ports:
      - "8190:21117"
      - "8192:21119"
    volumes:
      - ./data:/root
    networks:
      - rustdesk-net
    restart: unless-stopped

  hbbs:
    container_name: hbbs
    build: .
    image: rustdesk/rustdesk-server:local
    command: hbbs -r 15.207.161.44:8190
    depends_on:
      - hbbr
    ports:
      - "8188:21115"
      - "8189:21116"
      - "8189:21116/udp"
      - "8191:21118"
    volumes:
      - ./data:/root
    networks:
      - rustdesk-net
    restart: unless-stopped

  debug:
    image: rustdesk/rustdesk-server:local
    container_name: hbbs_debug
    # override the default command so the container stays up and provides a shell
    entrypoint: ["/bin/bash", "-c"]
    command: ["while true; do sleep 3600; done"]
    volumes:
      - ./data:/root
    networks:
      - rustdesk-net
    restart: unless-stopped
