services:
  hbbs:
    image: rustdesk/rustdesk-server:latest
    container_name: hbbs
    restart: unless-stopped
    environment:
      - RUST_LOG=info
      # Default ports, no need to override HBBS_PORT/HBBR_PORT
    command: hbbs
    ports:
      - "8188:21115"         # TCP ID/Signaling
      - "8187:21116/udp"     # UDP NAT traversal
      - "8189:21117"         # TCP relay coordination
    volumes:
      - ./data:/root/.config/rustdesk

  hbbr:
    image: rustdesk/rustdesk-server:latest
    container_name: hbbr
    restart: unless-stopped
    environment:
      - RUST_LOG=info
      # Default HBBR_PORT=21118 automatically
    command: hbbr
    ports:
      - "8190:21118"         # TCP relay
      - "8190:21118/udp"     # UDP relay
    volumes:
      - ./data:/root/.config/rustdesk
