services:
  hbbs:
    image: rustdesk/rustdesk-server:latest
    container_name: hbbs
    restart: unless-stopped
    command: hbbs
    ports:
      - "8188:21115"         # TCP for ID/Signaling
      - "8187:21116"         # TCP for ID registration and heartbeat
      - "8187:21116/udp"     # UDP for ID registration and heartbeat
      - "8189:21118"         # TCP for web client support
    volumes:
      - ./data:/root/.config/rustdesk

  hbbr:
    image: rustdesk/rustdesk-server:latest
    container_name: hbbr
    restart: unless-stopped
    command: hbbr
    ports:
      - "8190:21117"         # TCP relay
      - "8191:21119"         # TCP relay for web client
    volumes:
      - ./data:/root/.config/rustdesk