version: "3.8"

services:
  hbbs:
    image: rustdesk/rustdesk-server:latest
    container_name: hbbs
    restart: unless-stopped
    environment:
      - RUST_LOG=info
      - HBBS_PORT=8190
      - HBBR_PORT=8192
    command: hbbs -k _
    ports:
      - "8190:8190"
      - "8190:8190/udp"
      - "21115:21115"
      - "21116:21116"
      - "21117:21117/udp"
    volumes:
      - ./data:/root/.config/rustdesk

  hbbr: # <--- Must be aligned with 'hbbs:' and nested under 'services:'
    image: rustdesk/rustdesk-server:latest
    container_name: hbbr
    restart: unless-stopped
    environment:
      - RUST_LOG=info
      - HBBR_PORT=8192
    command: hbbr -k _
    ports:
      - "8192:8192"
      - "8192:8192/udp" # <-- The UDP line for the fix
      - "21117:21117"
    volumes:
      - ./data:/root/.config/rustdesk
