version: '3'

networks:
  rustdesk-net:
    external: false

services:
  hbbs:
    container_name: hbbs
    ports:
      - 8186:21115
      - 8187:21116
      - 8187:21116/udp
      - 8189:21118
    image: rustdesk/rustdesk-server:latest
    command: hbbs -r your.rustdeskserver.host:8188
    environment:
      - ALWAYS_USE_RELAY=Y
    volumes:
      - ./data/server:/root
    networks:
      - rustdesk-net
    depends_on:
      - hbbr
    restart: unless-stopped

  hbbr:
    container_name: hbbr
    ports:
      - 8188:21117
      - 8190:21119
    image: rustdesk/rustdesk-server:latest
    command: hbbr
    volumes:
      - ./data/server:/root
    networks:
      - rustdesk-net
    restart: unless-stopped
